import { Question } from '@/types';

/**
 * 生活场景类扩展问题库（75个）
 * 每个场景15个问题
 */
export const EXTENDED_SCENARIO_QUESTIONS: Question[] = [
  // 职业发展类（15个）
  {
    id: 'career-001',
    category: { primary: 'scenario', secondary: 'career' },
    content: '你工作中的哪些时刻让你觉得最有成就感？',
    difficulty: 2,
    tags: ['成就', '工作', '自我价值'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'career-002',
    category: { primary: 'scenario', secondary: 'career' },
    content: '如果可以重新选择职业，你会选择什么？为什么？',
    difficulty: 3,
    tags: ['职业', '选择', '假设'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'career-003',
    category: { primary: 'scenario', secondary: 'career' },
    content: '工作中你最不愿意妥协的是什么？',
    difficulty: 3,
    tags: ['原则', '底线', '职业'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'career-004',
    category: { primary: 'scenario', secondary: 'career' },
    content: '你理想的工作环境是什么样的？',
    difficulty: 2,
    tags: ['环境', '理想', '工作'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'career-005',
    category: { primary: 'scenario', secondary: 'career' },
    content: '你如何看待工作和生活的平衡？',
    difficulty: 3,
    tags: ['平衡', '工作', '生活'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'career-006',
    category: { primary: 'scenario', secondary: 'career' },
    content: '哪项技能对你的职业生涯影响最大？',
    difficulty: 2,
    tags: ['技能', '职业', '成长'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'career-007',
    category: { primary: 'scenario', secondary: 'career' },
    content: '你如何应对职场中的压力和挑战？',
    difficulty: 3,
    tags: ['压力', '挑战', '应对'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'career-008',
    category: { primary: 'scenario', secondary: 'career' },
    content: '工作中你最想改变的一件事是什么？',
    difficulty: 3,
    tags: ['改变', '工作', '反思'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'career-009',
    category: { primary: 'scenario', secondary: 'career' },
    content: '你认为自己最大的职业优势是什么？',
    difficulty: 2,
    tags: ['优势', '职业', '自我认知'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'career-010',
    category: { primary: 'scenario', secondary: 'career' },
    content: '你如何定义职业上的"成功"？',
    difficulty: 3,
    tags: ['成功', '定义', '价值观'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'career-011',
    category: { primary: 'scenario', secondary: 'career' },
    content: '如果让你给刚入职的自己一个建议，会是什么？',
    difficulty: 3,
    tags: ['建议', '经验', '成长'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'career-012',
    category: { primary: 'scenario', secondary: 'career' },
    content: '你更喜欢独立工作还是团队协作？为什么？',
    difficulty: 2,
    tags: ['工作方式', '独立', '团队'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'career-013',
    category: { primary: 'scenario', secondary: 'career' },
    content: '什么样的领导风格最能激励你？',
    difficulty: 3,
    tags: ['领导', '激励', '管理'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'career-014',
    category: { primary: 'scenario', secondary: 'career' },
    content: '你如何处理工作中的分歧和冲突？',
    difficulty: 3,
    tags: ['冲突', '沟通', '职场'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'career-015',
    category: { primary: 'scenario', secondary: 'career' },
    content: '5年后你希望在职业上达到什么状态？',
    difficulty: 4,
    tags: ['规划', '未来', '职业'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },

  // 创意激发类（15个）
  {
    id: 'scenario-creative-001',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '如果在荒岛上生活，你会如何记录自己的想法？',
    difficulty: 4,
    tags: ['创意', '困境', '表达'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'scenario-creative-002',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '你能用三个不相关的物品创造一个新发明吗？',
    difficulty: 4,
    tags: ['创意', '发明', '组合'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'scenario-creative-003',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '如果颜色有味道，红色会是什么味道？',
    difficulty: 3,
    tags: ['感官', '联想', '创意'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'scenario-creative-004',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '你能为一棵树设计一个完全不同的功能吗？',
    difficulty: 4,
    tags: ['创意', '设计', '重构'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'scenario-creative-005',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '如果文字消失了，人类如何传递思想？',
    difficulty: 4,
    tags: ['假设', '表达', '创意'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'scenario-creative-006',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '你能为一个普通的杯子设计10种新用途吗？',
    difficulty: 3,
    tags: ['创意', '用途', '发散'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'scenario-creative-007',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '如果梦境可以像电影一样观看，你想看谁的梦？',
    difficulty: 4,
    tags: ['梦境', '创意', '想象'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'scenario-creative-008',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '你能发明一个全新的节日吗？主题和庆祝方式是什么？',
    difficulty: 4,
    tags: ['创意', '节日', '文化'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'scenario-creative-009',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '如果城市是一个巨大的游戏，规则会是什么？',
    difficulty: 4,
    tags: ['创意', '游戏', '城市'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'scenario-creative-010',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '你能为"沉默"这个概念设计一个可视化形式吗？',
    difficulty: 5,
    tags: ['抽象', '可视化', '创意'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'scenario-creative-011',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '如果人类不再需要睡眠，多出来的8小时你会做什么？',
    difficulty: 3,
    tags: ['假设', '时间', '生活'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'scenario-creative-012',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '你能设计一个全新的交通工具吗？不需要符合物理定律',
    difficulty: 4,
    tags: ['创意', '交通', '设计'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'scenario-creative-013',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '如果建筑物可以根据心情变色，世界会是什么样？',
    difficulty: 3,
    tags: ['想象', '建筑', '情绪'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'scenario-creative-014',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '你能为一首从未听过的歌写一个故事吗？',
    difficulty: 4,
    tags: ['音乐', '故事', '创意'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'scenario-creative-015',
    category: { primary: 'scenario', secondary: 'creative' },
    content: '如果可以重新设计人类的一项身体功能，你会选哪个？',
    difficulty: 5,
    tags: ['创意', '人体', '设计'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },

  // 人际关系类（15个）
  {
    id: 'relationship-001',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '你如何定义"真正的朋友"？',
    difficulty: 3,
    tags: ['友谊', '定义', '关系'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'relationship-002',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '你在人际关系中最看重什么品质？',
    difficulty: 2,
    tags: ['品质', '关系', '价值观'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'relationship-003',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '如何处理与价值观不同的人的关系？',
    difficulty: 4,
    tags: ['差异', '包容', '关系'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'relationship-004',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '你在社交场合中是主动还是被动？为什么？',
    difficulty: 2,
    tags: ['社交', '性格', '自我认知'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'relationship-005',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '你如何维护一段重要但渐行渐远的关系？',
    difficulty: 4,
    tags: ['维护', '关系', '成长'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'relationship-006',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '什么情况下你会选择结束一段关系？',
    difficulty: 4,
    tags: ['底线', '决定', '关系'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'relationship-007',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '你在亲密关系中最大的恐惧是什么？',
    difficulty: 4,
    tags: ['恐惧', '亲密', '关系'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'relationship-008',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '你如何表达对别人的关心和爱？',
    difficulty: 2,
    tags: ['表达', '情感', '关系'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'relationship-009',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '你在人际关系中最容易犯的错误是什么？',
    difficulty: 3,
    tags: ['反思', '错误', '成长'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'relationship-010',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '你如何看待"君子之交淡如水"这句话？',
    difficulty: 3,
    tags: ['友谊', '哲学', '关系'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'relationship-011',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '你在团队合作中通常扮演什么角色？',
    difficulty: 2,
    tags: ['团队', '角色', '协作'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'relationship-012',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '如何平衡给予和索取在关系中的比例？',
    difficulty: 4,
    tags: ['平衡', '给予', '关系'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'relationship-013',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '你从父母身上学到的最重要的人际关系教训是什么？',
    difficulty: 3,
    tags: ['家庭', '经验', '关系'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'relationship-014',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '你如何应对社交中的孤独感？',
    difficulty: 3,
    tags: ['孤独', '社交', '情感'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'relationship-015',
    category: { primary: 'scenario', secondary: 'relationship' },
    content: '如果可以给所有人一条关于人际关系的建议，你会说什么？',
    difficulty: 3,
    tags: ['建议', '智慧', '关系'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },

  // 学习成长类（15个）
  {
    id: 'learning-001',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '你最近一次从失败中学到的重要教训是什么？',
    difficulty: 3,
    tags: ['失败', '教训', '成长'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'learning-002',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '你是如何学习新技能的？有什么独特的方法？',
    difficulty: 2,
    tags: ['方法', '学习', '技能'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'learning-003',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '哪本书或哪个课程对你的影响最大？',
    difficulty: 2,
    tags: ['阅读', '影响', '学习'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'learning-004',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '你如何在忙碌的生活中保持学习习惯？',
    difficulty: 3,
    tags: ['习惯', '时间', '学习'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'learning-005',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '你最想深入学习的领域是什么？为什么？',
    difficulty: 2,
    tags: ['兴趣', '领域', '学习'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'learning-006',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '你如何克服学习中的挫折和瓶颈？',
    difficulty: 3,
    tags: ['挫折', '瓶颈', '坚持'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'learning-007',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '理论与实践，你更倾向于哪个？为什么？',
    difficulty: 3,
    tags: ['理论', '实践', '学习'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'learning-008',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '你如何判断自己是否真正掌握了某项知识？',
    difficulty: 3,
    tags: ['掌握', '评估', '学习'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'learning-009',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '学习过程中，什么让你最有成就感？',
    difficulty: 2,
    tags: ['成就', '学习', '动力'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'learning-010',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '你如何选择要学习的内容？有什么标准？',
    difficulty: 3,
    tags: ['选择', '标准', '学习'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'learning-011',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '你更喜欢独自学习还是与他人一起学习？',
    difficulty: 2,
    tags: ['方式', '学习', '社交'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'learning-012',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '如何将学到的知识应用到实际生活中？',
    difficulty: 3,
    tags: ['应用', '实践', '知识'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'learning-013',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '你如何保持对新事物的好奇心？',
    difficulty: 3,
    tags: ['好奇心', '心态', '成长'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'learning-014',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '你认为自己最大的学习障碍是什么？',
    difficulty: 3,
    tags: ['障碍', '反思', '学习'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'learning-015',
    category: { primary: 'scenario', secondary: 'learning' },
    content: '如果可以向任何人学习一项技能，你会选择谁和什么技能？',
    difficulty: 3,
    tags: ['榜样', '技能', '学习'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },

  // 生活哲学类（15个）
  {
    id: 'philosophy-001',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '你认为生活的意义是什么？',
    difficulty: 4,
    tags: ['意义', '生活', '哲学'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'philosophy-002',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '你如何定义"幸福"？',
    difficulty: 3,
    tags: ['幸福', '定义', '价值观'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'philosophy-003',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '自由和责任，你认为哪个更重要？',
    difficulty: 4,
    tags: ['自由', '责任', '选择'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'philosophy-004',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '你如何看待物质追求和精神追求的平衡？',
    difficulty: 4,
    tags: ['物质', '精神', '平衡'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'philosophy-005',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '生活中什么让你感到最充实？',
    difficulty: 3,
    tags: ['充实', '生活', '满足'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'philosophy-006',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '你如何理解"活在当下"这句话？',
    difficulty: 3,
    tags: ['当下', '正念', '生活'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'philosophy-007',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '你认为人应该为未来牺牲现在的快乐吗？',
    difficulty: 4,
    tags: ['未来', '现在', '选择'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'philosophy-008',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '你如何面对生活中的不确定性？',
    difficulty: 4,
    tags: ['不确定性', '应对', '心态'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'philosophy-009',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '什么对你来说是"足够好"的生活标准？',
    difficulty: 4,
    tags: ['标准', '生活', '价值观'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'philosophy-010',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '你如何看待"简单生活"这个理念？',
    difficulty: 3,
    tags: ['简单', '生活', '哲学'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'philosophy-011',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '你认为生活中什么最值得珍惜？',
    difficulty: 3,
    tags: ['珍惜', '价值观', '生活'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'philosophy-012',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '你如何理解"知足常乐"和"追求更好"之间的关系？',
    difficulty: 4,
    tags: ['知足', '追求', '平衡'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'philosophy-013',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '生活中最大的悖论是什么？你如何应对它？',
    difficulty: 5,
    tags: ['悖论', '哲学', '思考'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'philosophy-014',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '你认为人生有"正确"的道路吗？',
    difficulty: 4,
    tags: ['道路', '人生', '选择'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'philosophy-015',
    category: { primary: 'scenario', secondary: 'philosophy' },
    content: '如果可以用一句话总结你的人生态度，会是什么？',
    difficulty: 4,
    tags: ['态度', '人生', '总结'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
];
