import { Question } from '@/types';

/**
 * 扩展问题库 - 新增75个问题
 * 与原有25个问题合并，总计100个问题
 */
export const EXTENDED_QUESTIONS: Question[] = [
  // ========== 假设思维 (新增15个) ==========
  {
    id: 'hypothesis-006',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果可以和未来的自己对话，你想问什么？',
    difficulty: 3,
    tags: ['假设', '未来', '自我'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'hypothesis-007',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果你可以选择在任何时代生活，你会选择哪个时代？为什么？',
    difficulty: 2,
    tags: ['假设', '历史', '价值观'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'hypothesis-008',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果每个人都诚实一天，世界会变成什么样？',
    difficulty: 4,
    tags: ['假设', '诚实', '社会'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'hypothesis-009',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果你拥有读心术，你会如何使用？',
    difficulty: 3,
    tags: ['假设', '能力', '伦理'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'hypothesis-010',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果地球上没有互联网，你的生活会怎样改变？',
    difficulty: 3,
    tags: ['假设', '科技', '生活方式'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'hypothesis-011',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果你可以瞬间掌握一项技能，你会选择什么？',
    difficulty: 2,
    tags: ['假设', '技能', '成长'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'hypothesis-012',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果让你设计一个理想的一周，你会怎么安排？',
    difficulty: 2,
    tags: ['假设', '生活', '规划'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'hypothesis-013',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果可以获得任何一种超能力，但只能用来帮助他人，你会选择什么？',
    difficulty: 4,
    tags: ['假设', '利他', '价值观'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'hypothesis-014',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果你能看到100年后的世界，你最想验证什么？',
    difficulty: 3,
    tags: ['假设', '未来', '好奇心'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'hypothesis-015',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果所有的工作都能被AI完成，人类会专注于什么？',
    difficulty: 4,
    tags: ['假设', 'AI', '未来', '意义'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'hypothesis-016',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果你的生活是一部电影，会是哪种类型的电影？',
    difficulty: 2,
    tags: ['假设', '生活', '自我认知'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'hypothesis-017',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果可以给10年前的自己一封信，你会写什么？',
    difficulty: 3,
    tags: ['假设', '过去', '反思'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'hypothesis-018',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果世界上的所有知识都能下载到大脑，你会怎么安排学习顺序？',
    difficulty: 3,
    tags: ['假设', '学习', '知识'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'hypothesis-019',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果你可以创造一个节日，这个节日会庆祝什么？',
    difficulty: 3,
    tags: ['假设', '创意', '文化'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'hypothesis-020',
    category: { primary: 'thinking', secondary: 'hypothesis' },
    content: '如果可以和任何历史人物共进晚餐，你会选择谁？会聊什么？',
    difficulty: 2,
    tags: ['假设', '历史', '对话'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },

  // ========== 逆向思考 (新增15个) ==========
  {
    id: 'reverse-006',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意浪费一个人的才能？',
    difficulty: 3,
    tags: ['逆向', '人才', '管理'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reverse-007',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意让一个创意想法被否决？',
    difficulty: 3,
    tags: ['逆向', '创意', '会议'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reverse-008',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意让用户不再使用你的产品？',
    difficulty: 3,
    tags: ['逆向', '产品', '用户体验'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reverse-009',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意破坏团队的信任？',
    difficulty: 4,
    tags: ['逆向', '团队', '信任'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reverse-010',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意让一个学习计划失败？',
    difficulty: 2,
    tags: ['逆向', '学习', '规划'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reverse-011',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意让一个设计作品变得难以理解？',
    difficulty: 3,
    tags: ['逆向', '设计', '沟通'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reverse-012',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意让一次演讲毫无影响力？',
    difficulty: 3,
    tags: ['逆向', '演讲', '表达'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reverse-013',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意扼杀一个创新想法？',
    difficulty: 4,
    tags: ['逆向', '创新', '管理'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reverse-014',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意让一段关系变得紧张？',
    difficulty: 3,
    tags: ['逆向', '关系', '沟通'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reverse-015',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意让一个会议效率最低？',
    difficulty: 2,
    tags: ['逆向', '会议', '效率'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reverse-016',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意让一个品牌失去用户信任？',
    difficulty: 4,
    tags: ['逆向', '品牌', '信任'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reverse-017',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意让自己变得不快乐？',
    difficulty: 3,
    tags: ['逆向', '快乐', '心理'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reverse-018',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意让一篇文章没人想读？',
    difficulty: 2,
    tags: ['逆向', '写作', '内容'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reverse-019',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意让一个APP被用户卸载？',
    difficulty: 3,
    tags: ['逆向', '产品', '体验'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reverse-020',
    category: { primary: 'thinking', secondary: 'reverse' },
    content: '如何故意让一个社区变得死气沉沉？',
    difficulty: 4,
    tags: ['逆向', '社区', '运营'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },

  // ========== 联想创意 (新增15个) ==========
  {
    id: 'creative-006',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '森林 + 数据 = ？',
    difficulty: 4,
    tags: ['联想', '自然', '科技'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'creative-007',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '跑步 + 阅读 = ？',
    difficulty: 3,
    tags: ['联想', '运动', '学习'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'creative-008',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '沉默 + 沟通 = ？',
    difficulty: 4,
    tags: ['联想', '沟通', '心理'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'creative-009',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '限制 + 创意 = ？',
    difficulty: 4,
    tags: ['联想', '创意', '约束'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'creative-010',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '错误 + 学习 = ？',
    difficulty: 3,
    tags: ['联想', '失败', '成长'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'creative-011',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '游戏 + 教育 = ？',
    difficulty: 3,
    tags: ['联想', '游戏', '教育'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'creative-012',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '孤独 + 社交 = ？',
    difficulty: 4,
    tags: ['联想', '社交', '心理'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'creative-013',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '慢生活 + 快节奏 = ？',
    difficulty: 3,
    tags: ['联想', '生活', '节奏'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'creative-014',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '东方 + 西方 = ？',
    difficulty: 3,
    tags: ['联想', '文化', '融合'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'creative-015',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '简洁 + 复杂 = ？',
    difficulty: 4,
    tags: ['联想', '设计', '哲学'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'creative-016',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '童年 + 成年 = ？',
    difficulty: 3,
    tags: ['联想', '成长', '回忆'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'creative-017',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '理性 + 感性 = ？',
    difficulty: 4,
    tags: ['联想', '思维', '决策'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'creative-018',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '个人 + 集体 = ？',
    difficulty: 4,
    tags: ['联想', '团队', '社会'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'creative-019',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '给予 + 接受 = ？',
    difficulty: 4,
    tags: ['联想', '关系', '心理'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'creative-020',
    category: { primary: 'thinking', secondary: 'creative' },
    content: '自由 + 纪律 = ？',
    difficulty: 4,
    tags: ['联想', '生活', '哲学'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },

  // ========== 自我反思 (新增15个) ==========
  {
    id: 'reflection-006',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你最近一次感到"这就是我"是什么时候？',
    difficulty: 3,
    tags: ['反思', '身份', '真实'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reflection-007',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你的哪项特质最让朋友欣赏？',
    difficulty: 2,
    tags: ['反思', '优点', '友谊'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reflection-008',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你在什么情况下最不像自己？',
    difficulty: 3,
    tags: ['反思', '自我', '状态'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reflection-009',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你最常对自己说的谎是什么？',
    difficulty: 4,
    tags: ['反思', '诚实', '心理'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reflection-010',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你的童年梦想是什么？现在看来呢？',
    difficulty: 3,
    tags: ['反思', '童年', '梦想'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reflection-011',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你在什么情况下最有创造力？',
    difficulty: 2,
    tags: ['反思', '创意', '状态'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reflection-012',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你的决策通常是理性的还是感性的？',
    difficulty: 3,
    tags: ['反思', '决策', '思维'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reflection-013',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你最有成就感的是什么？',
    difficulty: 2,
    tags: ['反思', '成就', '价值'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reflection-014',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你最大的遗憾是什么？为什么？',
    difficulty: 3,
    tags: ['反思', '遗憾', '过去'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reflection-015',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你更喜欢做计划的执行者还是做计划的策划者？',
    difficulty: 2,
    tags: ['反思', '角色', '工作'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reflection-016',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你的朋友圈是如何影响你的？',
    difficulty: 3,
    tags: ['反思', '社交', '影响'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reflection-017',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你在压力下通常会做什么反应？',
    difficulty: 3,
    tags: ['反思', '压力', '应对'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reflection-018',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你最重要的价值观是什么？',
    difficulty: 3,
    tags: ['反思', '价值观', '优先级'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reflection-019',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你做过最勇敢的决定是什么？',
    difficulty: 3,
    tags: ['反思', '勇敢', '决定'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'reflection-020',
    category: { primary: 'thinking', secondary: 'reflection' },
    content: '你希望别人如何评价你？',
    difficulty: 2,
    tags: ['反思', '评价', '印象'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },

  // ========== 未来设想 (新增15个) ==========
  {
    id: 'future-006',
    category: { primary: 'thinking', secondary: 'future' },
    content: '3年后的你希望自己有什么改变？',
    difficulty: 3,
    tags: ['未来', '成长', '规划'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'future-007',
    category: { primary: 'thinking', secondary: 'future' },
    content: '如果5年后你必须离开现在的领域，你会去做什么？',
    difficulty: 4,
    tags: ['未来', '转型', '职业'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'future-008',
    category: { primary: 'thinking', secondary: 'future' },
    content: '你希望自己60岁时是什么样的人？',
    difficulty: 3,
    tags: ['未来', '老年', '人生'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'future-009',
    category: { primary: 'thinking', secondary: 'future' },
    content: '未来的你想给现在的自己什么建议？',
    difficulty: 3,
    tags: ['未来', '建议', '智慧'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'future-010',
    category: { primary: 'thinking', secondary: 'future' },
    content: '你理想的工作日是怎样的？',
    difficulty: 2,
    tags: ['未来', '工作', '理想'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'future-011',
    category: { primary: 'thinking', secondary: 'future' },
    content: '你想在哪个城市生活？为什么？',
    difficulty: 2,
    tags: ['未来', '生活', '城市'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'future-012',
    category: { primary: 'thinking', secondary: 'future' },
    content: '10年后你希望拥有什么技能？',
    difficulty: 3,
    tags: ['未来', '技能', '学习'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'future-013',
    category: { primary: 'thinking', secondary: 'future' },
    content: '你希望自己的墓志铭写什么？',
    difficulty: 4,
    tags: ['未来', '死亡', '遗产'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'future-014',
    category: { primary: 'thinking', secondary: 'future' },
    content: '你最想发明什么来改变世界？',
    difficulty: 4,
    tags: ['未来', '发明', '影响'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'future-015',
    category: { primary: 'thinking', secondary: 'future' },
    content: '如果你能成为某个领域的顶尖专家，会是哪个领域？',
    difficulty: 3,
    tags: ['未来', '专业', '目标'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'future-016',
    category: { primary: 'thinking', secondary: 'future' },
    content: '你希望5年后的自己拥有哪些人脉？',
    difficulty: 3,
    tags: ['未来', '人脉', '社交'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'future-017',
    category: { primary: 'thinking', secondary: 'future' },
    content: '未来一年你最想学会的3件事是什么？',
    difficulty: 2,
    tags: ['未来', '学习', '目标'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'future-018',
    category: { primary: 'thinking', secondary: 'future' },
    content: '你希望自己有什么被动收入来源？',
    difficulty: 3,
    tags: ['未来', '财务', '被动收入'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'future-019',
    category: { primary: 'thinking', secondary: 'future' },
    content: '你想达到什么样的工作生活平衡？',
    difficulty: 3,
    tags: ['未来', '平衡', '生活'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
  {
    id: 'future-020',
    category: { primary: 'thinking', secondary: 'future' },
    content: '你希望家庭生活是什么样子的？',
    difficulty: 3,
    tags: ['未来', '家庭', '生活'],
    createdAt: new Date('2024-01-01'),
    answerCount: 0,
  },
];

/**
 * 获取所有问题（原有25个 + 新增75个 = 100个）
 */
export function getAllQuestions(): Question[] {
  // 这里需要导入原有的问题
  // 暂时返回扩展问题，后续会合并
  return EXTENDED_QUESTIONS;
}
