-- ============================================================================
-- 万万没想到 - 全新数据库架构（本地优先 + 手动同步）
-- ============================================================================
-- 执行方式：在 Supabase Dashboard 的 SQL Editor 中执行
-- ============================================================================

-- 第一步：删除所有旧表
-- ============================================================================

DROP TABLE IF EXISTS public.riddle_records CASCADE;
DROP TABLE IF EXISTS public.yes_or_no_records CASCADE;
DROP TABLE IF EXISTS public.guess_number_records CASCADE;
DROP TABLE IF EXISTS public.writing_challenge_works CASCADE;
DROP TABLE IF EXISTS public.slot_machine_results CASCADE;
DROP TABLE IF EXISTS public.turtle_soup_records CASCADE;
DROP TABLE IF EXISTS public.answers CASCADE;
DROP TABLE IF EXISTS public.favorites CASCADE;
DROP TABLE IF EXISTS public.collections CASCADE;
DROP TABLE IF EXISTS public.later_questions CASCADE;
DROP TABLE IF EXISTS public.user_progress CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.user_data CASCADE;

-- 第二步：创建简化的数据表结构
-- ============================================================================

-- 1. 用户资料表（只存储基本资料信息）
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  username TEXT,
  avatar_url TEXT,
  bio TEXT,
  gender TEXT,
  age INTEGER,
  birthday DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- 2. 通用用户数据表（存储所有用户数据）
-- 所有用户数据（回答、收藏、进度等）都以 JSON 格式存储在此表中
CREATE TABLE public.user_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  key TEXT NOT NULL,              -- 数据键，如 'wwx-answers', 'wwx-favorites' 等
  data JSONB NOT NULL,            -- 实际数据（JSON 格式）
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  UNIQUE(user_id, key)            -- 确保每个用户的每个键唯一
);

-- 第三步：创建索引
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_user_data_user_id ON public.user_data(user_id);
CREATE INDEX IF NOT EXISTS idx_user_data_key ON public.user_data(key);

-- 第四步：创建触发器函数
-- ============================================================================

-- 更新时间戳函数
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc', NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 为 profiles 表添加更新时间戳触发器
DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
CREATE TRIGGER update_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- 为 user_data 表添加更新时间戳触发器
DROP TRIGGER IF EXISTS update_user_data_updated_at ON public.user_data;
CREATE TRIGGER update_user_data_updated_at
  BEFORE UPDATE ON public.user_data
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- 自动创建用户资料函数
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, username)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(
      NEW.raw_user_meta_data->>'full_name',
      NEW.raw_user_meta_data->>'name',
      split_part(NEW.email, '@', 1)
    )
  );
  RETURN NEW;
EXCEPTION
  WHEN unique_violation THEN
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 创建用户资料触发器
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- 第五步：启用 RLS 并创建策略
-- ============================================================================

-- 启用 RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_data ENABLE ROW LEVEL SECURITY;

-- Profiles 策略
CREATE POLICY "Users can view their own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Public profiles are viewable by everyone"
  ON public.profiles FOR SELECT
  USING (true);

-- User data 策略（简化版 - 用户完全控制自己的数据）
CREATE POLICY "Users can manage their own data"
  ON public.user_data FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 第六步：验证和测试
-- ============================================================================

-- 验证表是否创建成功
SELECT
  '✅ 所有表已创建' as status,
  (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public') as table_count;

-- 显示所有表
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;

-- 显示表结构
SELECT
  column_name,
  data_type,
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name IN ('profiles', 'user_data')
ORDER BY table_name, ordinal_position;

-- ============================================================================
-- ✅ 数据库重建完成！
-- ============================================================================
-- 新架构说明：
-- 1. profiles: 存储用户基本资料（邮箱、用户名、头像等）
-- 2. user_data: 通用数据表，存储所有用户数据（JSON 格式）
--    - key: 数据键（如 'wwx-answers', 'wwx-favorites' 等）
--    - data: 实际数据（JSON 格式）
--
-- 存储策略：
-- - 登录用户：平时使用本地存储，手动同步到云端
-- - 游客用户：始终使用本地存储
-- - 退出登录：自动同步本地数据到云端
-- ============================================================================
